# Generated by Django 5.2.1 on 2025-06-02 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeOffer',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad_receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_to_take', to='ads.ad')),
                ('ad_sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_to_give', to='ads.ad')),
            ],
        ),
    ]
