# Generated by Django 5.2.1 on 2025-06-04 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExchangeOffer',
            new_name='ExchangeProposal',
        ),
    ]
